# https://github.com/realm/SwiftLint

disabled_rules:
  - line_length
  - file_length
  - function_parameter_count
  - force_cast
  - force_try
  - force_unwrapping
  - identifier_name

function_body_length:
  warning: 100
  error: 200

cyclomatic_complexity:
  ignores_case_statements: true

excluded:
  - Carthage
  - Pods
